name: SocialFusion
options:
  bundleIdPrefix: com.socialfusion
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: "14.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

targets:
  SocialFusion:
    type: application
    platform: iOS
    sources:
      - path: SocialFusion
        excludes:
          - Networking/NetworkError.swift
          - Views/Utilities/URLServiceWrapper.swift
          - Views/Components/FullscreenMediaView.swift
          - Extensions/NotificationCenter+Extensions.swift
          - Models/TimelineState+Bridge.swift
          - Models/TimelineState+Verification.swift
          - Models/TimelineState+Phase2Verification.swift
          - Views/TestingView.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.socialfusionapp.app
        PRODUCT_NAME: SocialFusion
        SWIFT_VERSION: 5.0
        DEVELOPMENT_TEAM: $(TEAM_ID)
        INFOPLIST_FILE: SocialFusion/Info.plist
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: $(GITHUB_RUN_NUMBER)
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_SPECIFIER: $(PROFILE_NAME)
    info:
      path: SocialFusion/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        "UISupportedInterfaceOrientations~ipad":
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: false
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate

schemes:
  SocialFusion:
    build:
      targets:
        SocialFusion: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release 